import { DocPage } from "@/components/docs/doc-page";

export const metadata = { title: "Methodology - EdgeHub" };

export default function MethodologyPage() {
  return (
    <DocPage title="Methodology" version="v1.0">
      <p>
        EdgeHub converts each sportsbook's posted odds into an implied probability, removes each book's own margin
        (the "vig") using proportional normalization, and averages the de-vigged probabilities across every currently
        eligible book to form a consensus estimate. Nothing here is generated by a language model - every number is a
        deterministic calculation, and it is versioned and stored alongside the inputs that produced it.
      </p>
      <h2 className="font-display text-lg font-semibold">Freshness gating</h2>
      <p>
        A quote is only used in consensus or ranking while it is "current" or "aging" under its market's configured
        SLA. Quotes that are stale, from an unavailable provider, or pending identity-mapping review are excluded
        rather than treated as current - "freshness before flash" is the product's first principle, not a slogan.
      </p>
      <h2 className="font-display text-lg font-semibold">Edge, EV, and the Opportunity Score</h2>
      <p>
        Edge is the difference, in percentage points, between the consensus estimate and the implied probability of
        the best currently eligible price. Expected value (EV) is the average return per $1 staked if that estimate
        is correct across many similar bets - never a promise for a single event. The Opportunity Score blends edge
        percentile, price advantage, consensus depth, a liquidity proxy, price stability, and freshness into a single
        0-100 ranking aid; it is explicitly not a win probability.
      </p>
      <h2 className="font-display text-lg font-semibold">AI explanations</h2>
      <p>
        When you request an explanation, the model receives only structured evidence already computed by the
        application - current quotes, consensus, edge, EV, and known data limitations. It is instructed to cite only
        that evidence, never to invent injuries, news, or a probability of its own, and every output is validated
        against a fixed schema before it reaches you.
      </p>
      <p>Full formula reference is available on request; the golden test-vector suite backing every calculation above is part of this product's engineering handoff package.</p>
    </DocPage>
  );
}
